### PR TITLE
Fix content overflow on smaller screens

### LINKED ISSUE #131: Fix content overflow
Modify the CSS code to fix the following overflows, that appear when changing the screen size :

### PR DESCRIPTION
**Pull request by Okibe00**
# Description
Changes improved responsiveness up to a dimension of 218 x 892.

Fixes #131.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue).

## Checklist

- [x] I have a descriptive title for my PR
- [x] I have linked this PR to the corresponding issue. [See how to do that here.](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [x] I have run the project locally and reviewed the code changes
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by sparkO7 — CHANGES_REQUESTED** [review]
Hi, Okibe.

Your changes are good for the smaller screens. But, this caused some changes for the larger screens. (Ex, the 'inputs-row' is too wide and the 'result-row' is a bit narrow).

**Comment by Okibe00** [comment]
Hi @sparkO7 can you take a screen grab at your end so I can see how it looks.

**Comment by sparkO7** [comment]
This is before: 



And after:

**Review by AndreyDmitriev39r — APPROVED** [review]
I don't see any overflow.
I checked screen width from 300 to 1300 px.
I am approving it.
*Note for future*
Our media query breakpoints need to be adjusted properly, some dimensions look weird

**Review by sparkO7 — APPROVED** [review]
LGTM 👍

**Pull request merged**
