### PR TITLE
Handling HSL invalid input errors

### LINKED ISSUE #128: Create user message for invalid inputs for HSL functionality
We should display an invalid input message, when the user does not input the proper format for HSL value.

image

### PR DESCRIPTION
**Pull request by AndreyDmitriev39r**
# Description

Fixes #128

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Chore items (this includes basic clean up of files, or updates to packages)
- [ ] Updates to documentation

## Checklist

- [x] I have a descriptive title for my PR
- [x] I have linked this PR to the corresponding issue. [See how to do that here.](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [x] I have run the project locally and reviewed the code changes
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by AndreyDmitriev39r** [comment]
I think regular expression is mostly fine, need to double check how exactly I want to deal with `%` symbols - maybe they should be required strictly - I will deal with it.

Looking at files changed - I think I resolved merge conflict ok, but I need some feedback about that already, if there are some new issues because of resolving conflict - it is better to detect them ASAP.

Known issue - error messages for valid inputs.
Possible options to fix - some refactoring of `if..else` chain. I hope I will not need to touch RGB logic. But I think it is not possible - currrent `if...else` chain for RGB is conflicting with `if...else` chain I built for HSL

**Review by Okibe00 — COMMENTED** [review]
The percentage sign should be strictly required like you mentioned, I believe the  `hslNumbers` function can be optimized a little, instead of using replace and split, you can use `hslColor.match(/\d+/g)`.

**Review by sparkO7 — APPROVED** [review]
LGTM 👍

**Comment by dgupta0** [comment]
looks fine to me. I tested hsl colors on local computer. Though I don't understand exactly how the function works.

**Review by jdwilkin4 — APPROVED** [review]
Tested this locally and everything works on my end. 
Let's get this merged in 👍

**Pull request merged**
