### PR TITLE
codebase refactoring #138

### LINKED ISSUE #138: Move helper functions to helper.js file
**This should be worked on after version 1 is deployed**

Our current JavaScript file is a little bloated right now. 
One of the ways we can clean it up is to move all of the helper functions into the `helpers.js` file. 

Examples would include `getLuminance`, `isItNamedColor`, `shortToFullHex`, `hexToRGB`, etc. 

Go through the entire JS file and identify all of the helper functions that can be moved to the  `helpers.js` file. 

If you are new to imports/exports, here is a good article to read.
https://bobbyhadz.com/blog/javascript-import-function-from-another-file

### PR DESCRIPTION
**Pull request by Dorfieeee**
# Description

Okay. While I was cleaning up the index.js I also decided to refactor the whole index.js after moving helper functions.
It was a mess 🦠  and the HTML and CSS is still rather messy but it can be change over time.
There were several functions for one use only just to name the two or three lines of code.
Also, it seems that I fixed a bug 🐛 . The graphics label was not showing correct result.

I am not saying my version is perfect. It can be changed. I am opened for discussion 😸 

Fixes #138 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Chore items (this includes basic clean up of files, or updates to packages)
- [ ] Updates to documentation

## Checklist

- [x] I have a descriptive title for my PR
- [x] I have linked this PR to the corresponding issue. [See how to do that here.](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [x] I have run the project locally and reviewed the code changes
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by ChefDaddyJay — COMMENTED** [review]
It seems like the clearMessages function is a bit redundant unless we plan to have more messages to handle in the future. In which case, it might server to just keep an array of "active messages" and wrap the display/hide/clear functions in their own handler. As it stand, the app only ever displays one message at a time anyway, as far as I can tell. Just my thoughts.

**Comment by Dorfieeee** [comment]
I'm not sure what you mean. Could you make a suggestion.?

**Comment by ChefDaddyJay** [comment]
Ok, so I tried pushing something here, but I think I'm doing something wrong. Basically, all I'm saying is that the `clearMessages()` function in `index.js` isn't necessary. All it does is call the `hideMessage()` function twice. Just making those two calls inside `handleChange()` is shorter, and saves a step. 

If we had more than two messages to handle, it might make sense to have a separate function to clear them, but for this version, it just seems like extra code (about 5 lines, I think)

**Comment by Dorfieeee** [comment]
Good enough. I was trying to cleanse the code from redundant functions like this one.

**Pull request merged**
